# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chart_panel_options.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(784, 465)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.widget_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_3)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_4)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_5)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_6)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.widget_5)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_7)
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_4.addWidget(self.label_32)
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_8)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_8 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setMidLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(self.frame_8)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_8)
        self.pushButton.setStyleSheet("background-color: rgb(214, 39, 40);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.frame_8)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_23 = QtWidgets.QLabel(self.frame_8)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 4, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_8)
        self.spinBox_2.setProperty("value", 25)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 0, 5, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.frame_8)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 127, 14);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_8)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_8)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 1, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_8)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 1, 4, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_8)
        self.spinBox_3.setProperty("value", 35)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_2.addWidget(self.spinBox_3, 1, 5, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.frame_8)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_3.setStyleSheet("background-color: rgb(219, 219, 141);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_8)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_8)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_8)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 2, 4, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_8)
        self.spinBox_4.setProperty("value", 45)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_2.addWidget(self.spinBox_4, 2, 5, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.frame_8)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_4.setStyleSheet("background-color: rgb(152, 223, 138);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_8)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_8)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 3, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_8)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 3, 4, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_8)
        self.spinBox_5.setProperty("value", 55)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_2.addWidget(self.spinBox_5, 3, 5, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.frame_8)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 4, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_5.setStyleSheet("background-color: rgb(44, 160, 44);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_8)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 4, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_8)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 4, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_8)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 4, 4, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_8)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 4, 5, 1, 2)
        self.verticalLayout.addWidget(self.frame_8)
        self.widget_7 = QtWidgets.QWidget(Dialog)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout.addWidget(self.widget_7)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(1)
        self.comboBox_2.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Chart Panel Options"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Chart Panel Grid and Display Options</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Rows:"))
        self.comboBox.setItemText(0, _translate("Dialog", "1"))
        self.comboBox.setItemText(1, _translate("Dialog", "2"))
        self.label_3.setText(_translate("Dialog", "Columns:"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "2"))
        self.label_4.setText(_translate("Dialog", "1."))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Peak Period Line"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Peak Period Bar"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Day over Time"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "Percent Day"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "Percent TMC"))
        self.label_5.setText(_translate("Dialog", "2."))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Peak Period Line"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "Peak Period Bar"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "Day over Time"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "Percent Day"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "Percent TMC"))
        self.label_6.setText(_translate("Dialog", "3."))
        self.comboBox_5.setItemText(0, _translate("Dialog", "Peak Period Line"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "Peak Period Bar"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "Day over Time"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "Percent Day"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "Percent TMC"))
        self.label_7.setText(_translate("Dialog", "4."))
        self.comboBox_6.setItemText(0, _translate("Dialog", "Peak Period Line"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "Peak Period Bar"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "Day over Time"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "Percent Day"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "Percent TMC"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">1</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">2</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">3</span></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">4</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "Number of Speed Bins:"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_7.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_7.setItemText(4, _translate("Dialog", "5"))
        self.label_32.setText(_translate("Dialog", "Speed Bin Color Scheme:"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "Default"))
        self.comboBox_8.setItemText(1, _translate("Dialog", "User"))
        self.label_13.setText(_translate("Dialog", "Speed Bin 1:"))
        self.pushButton.setText(_translate("Dialog", "Color 1"))
        self.label_18.setText(_translate("Dialog", "Speed Range:"))
        self.label_23.setText(_translate("Dialog", "To"))
        self.label_14.setText(_translate("Dialog", "Speed Bin 2:"))
        self.pushButton_2.setText(_translate("Dialog", "Color 2"))
        self.label_19.setText(_translate("Dialog", "Speed Range:"))
        self.label_28.setText(_translate("Dialog", "25"))
        self.label_24.setText(_translate("Dialog", "To"))
        self.label_15.setText(_translate("Dialog", "Speed Bin 3:"))
        self.pushButton_3.setText(_translate("Dialog", "Color 3"))
        self.label_20.setText(_translate("Dialog", "Speed Range:"))
        self.label_29.setText(_translate("Dialog", "35"))
        self.label_25.setText(_translate("Dialog", "To"))
        self.label_16.setText(_translate("Dialog", "Speed Bin 4:"))
        self.pushButton_4.setText(_translate("Dialog", "Color 4"))
        self.label_21.setText(_translate("Dialog", "Speed Range:"))
        self.label_30.setText(_translate("Dialog", "45"))
        self.label_26.setText(_translate("Dialog", "To"))
        self.label_17.setText(_translate("Dialog", "Speed Bin 5:"))
        self.pushButton_5.setText(_translate("Dialog", "Color 5"))
        self.label_22.setText(_translate("Dialog", "Speed Range:"))
        self.label_31.setText(_translate("Dialog", "55"))
        self.label_27.setText(_translate("Dialog", "To"))
        self.label_33.setText(_translate("Dialog", "Max"))

