# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_20180612.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1332, 873)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(-1, 2, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_5)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setVerticalSpacing(5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_agency = QtWidgets.QLabel(self.widget_5)
        self.label_agency.setObjectName("label_agency")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_agency)
        self.label_18 = QtWidgets.QLabel(self.widget_5)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.widget_5)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.label_project_name = QtWidgets.QLabel(self.widget_5)
        self.label_project_name.setObjectName("label_project_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_project_name)
        self.label_analyst = QtWidgets.QLabel(self.widget_5)
        self.label_analyst.setObjectName("label_analyst")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_analyst)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.toolBox = QtWidgets.QToolBox(self.widget_2)
        self.toolBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox  {\n"
"    padding: 5px;\n"
"    border: 1px transparent black;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    color: #eff0f1;\n"
"    background-color: #333333;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent #333333;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QToolBox::tab:selected { /* bold selected tabs */\n"
"    font: bold;\n"
"    background-color: #333333;\n"
"    border-color: #D1DBCB;\n"
" }\n"
"\n"
"QToolBox::tab:disabled { /* format disabled tabs */\n"
"    background-color: rgb(175, 175, 175);\n"
"    border-color: #D1DBCB;\n"
" }")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(0)
        self.toolBox.setObjectName("toolBox")
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setEnabled(True)
        self.page_15.setGeometry(QtCore.QRect(0, 0, 218, 276))
        self.page_15.setStyleSheet("")
        self.page_15.setObjectName("page_15")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_15)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_17 = QtWidgets.QLabel(self.page_15)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.page_15)
        self.treeWidget_3.setObjectName("treeWidget_3")
        self.verticalLayout.addWidget(self.treeWidget_3)
        self.pushButton_first_chart = QtWidgets.QPushButton(self.page_15)
        self.pushButton_first_chart.setObjectName("pushButton_first_chart")
        self.verticalLayout.addWidget(self.pushButton_first_chart)
        self.toolBox.addItem(self.page_15, "")
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setGeometry(QtCore.QRect(0, 0, 197, 313))
        self.page_16.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.page_16.setObjectName("page_16")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_16)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_3 = QtWidgets.QFrame(self.page_16)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.label_7 = QtWidgets.QLabel(self.page_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.ap_start1 = QtWidgets.QComboBox(self.page_16)
        self.ap_start1.setObjectName("ap_start1")
        self.verticalLayout_3.addWidget(self.ap_start1)
        self.ap_end1 = QtWidgets.QComboBox(self.page_16)
        self.ap_end1.setObjectName("ap_end1")
        self.verticalLayout_3.addWidget(self.ap_end1)
        self.line = QtWidgets.QFrame(self.page_16)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.label_8 = QtWidgets.QLabel(self.page_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.ap_start2 = QtWidgets.QComboBox(self.page_16)
        self.ap_start2.setObjectName("ap_start2")
        self.verticalLayout_3.addWidget(self.ap_start2)
        self.ap_end2 = QtWidgets.QComboBox(self.page_16)
        self.ap_end2.setObjectName("ap_end2")
        self.verticalLayout_3.addWidget(self.ap_end2)
        self.line_2 = QtWidgets.QFrame(self.page_16)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.label_9 = QtWidgets.QLabel(self.page_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.ap_start3 = QtWidgets.QComboBox(self.page_16)
        self.ap_start3.setObjectName("ap_start3")
        self.verticalLayout_3.addWidget(self.ap_start3)
        self.ap_end3 = QtWidgets.QComboBox(self.page_16)
        self.ap_end3.setObjectName("ap_end3")
        self.verticalLayout_3.addWidget(self.ap_end3)
        self.line_4 = QtWidgets.QFrame(self.page_16)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.pushButton_sec_chart = QtWidgets.QPushButton(self.page_16)
        self.pushButton_sec_chart.setObjectName("pushButton_sec_chart")
        self.verticalLayout_3.addWidget(self.pushButton_sec_chart)
        self.toolBox.addItem(self.page_16, "")
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setEnabled(True)
        self.page_19.setGeometry(QtCore.QRect(0, 0, 218, 187))
        self.page_19.setObjectName("page_19")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_19)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.page_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setWordWrap(False)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.cb_tmc_select = QtWidgets.QComboBox(self.page_19)
        self.cb_tmc_select.setObjectName("cb_tmc_select")
        self.verticalLayout_6.addWidget(self.cb_tmc_select)
        self.line_5 = QtWidgets.QFrame(self.page_19)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.label_15 = QtWidgets.QLabel(self.page_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.cb_stack_start = QtWidgets.QComboBox(self.page_19)
        self.cb_stack_start.setObjectName("cb_stack_start")
        self.verticalLayout_6.addWidget(self.cb_stack_start)
        self.label_10 = QtWidgets.QLabel(self.page_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.cb_stack_end = QtWidgets.QComboBox(self.page_19)
        self.cb_stack_end.setObjectName("cb_stack_end")
        self.verticalLayout_6.addWidget(self.cb_stack_end)
        self.line_6 = QtWidgets.QFrame(self.page_19)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_6.addWidget(self.line_6)
        self.toolBox.addItem(self.page_19, "")
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setGeometry(QtCore.QRect(0, 0, 197, 353))
        self.page_17.setObjectName("page_17")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_17)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.page_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.cb_tmc_select_trend = QtWidgets.QComboBox(self.page_17)
        self.cb_tmc_select_trend.setObjectName("cb_tmc_select_trend")
        self.verticalLayout_4.addWidget(self.cb_tmc_select_trend)
        self.line_10 = QtWidgets.QFrame(self.page_17)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_4.addWidget(self.line_10)
        self.widget_10 = QtWidgets.QWidget(self.page_17)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.check_mid = QtWidgets.QCheckBox(self.widget_10)
        self.check_mid.setObjectName("check_mid")
        self.gridLayout_4.addWidget(self.check_mid, 3, 0, 1, 2)
        self.check_am = QtWidgets.QCheckBox(self.widget_10)
        self.check_am.setChecked(True)
        self.check_am.setObjectName("check_am")
        self.gridLayout_4.addWidget(self.check_am, 1, 0, 1, 2)
        self.check_pm = QtWidgets.QCheckBox(self.widget_10)
        self.check_pm.setChecked(True)
        self.check_pm.setObjectName("check_pm")
        self.gridLayout_4.addWidget(self.check_pm, 2, 0, 1, 2)
        self.edit_trends_button = QtWidgets.QPushButton(self.widget_10)
        self.edit_trends_button.setObjectName("edit_trends_button")
        self.gridLayout_4.addWidget(self.edit_trends_button, 0, 2, 1, 2)
        self.trend_label_am = QtWidgets.QLabel(self.widget_10)
        self.trend_label_am.setAlignment(QtCore.Qt.AlignCenter)
        self.trend_label_am.setObjectName("trend_label_am")
        self.gridLayout_4.addWidget(self.trend_label_am, 1, 2, 1, 2)
        self.trend_label_pm = QtWidgets.QLabel(self.widget_10)
        self.trend_label_pm.setAlignment(QtCore.Qt.AlignCenter)
        self.trend_label_pm.setObjectName("trend_label_pm")
        self.gridLayout_4.addWidget(self.trend_label_pm, 2, 2, 1, 2)
        self.trend_label_mid = QtWidgets.QLabel(self.widget_10)
        self.trend_label_mid.setAlignment(QtCore.Qt.AlignCenter)
        self.trend_label_mid.setObjectName("trend_label_mid")
        self.gridLayout_4.addWidget(self.trend_label_mid, 3, 2, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.line_9 = QtWidgets.QFrame(self.page_17)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_4.addWidget(self.line_9)
        self.widget_9 = QtWidgets.QWidget(self.page_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.check_wkdy = QtWidgets.QCheckBox(self.widget_9)
        self.check_wkdy.setChecked(True)
        self.check_wkdy.setObjectName("check_wkdy")
        self.gridLayout_3.addWidget(self.check_wkdy, 0, 0, 1, 1)
        self.check_wknd = QtWidgets.QCheckBox(self.widget_9)
        self.check_wknd.setChecked(False)
        self.check_wknd.setObjectName("check_wknd")
        self.gridLayout_3.addWidget(self.check_wknd, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.line_7 = QtWidgets.QFrame(self.page_17)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_4.addWidget(self.line_7)
        self.widget_8 = QtWidgets.QWidget(self.page_17)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.check_mon = QtWidgets.QCheckBox(self.widget_8)
        self.check_mon.setChecked(True)
        self.check_mon.setObjectName("check_mon")
        self.gridLayout_2.addWidget(self.check_mon, 0, 0, 1, 1)
        self.check_sat = QtWidgets.QCheckBox(self.widget_8)
        self.check_sat.setObjectName("check_sat")
        self.gridLayout_2.addWidget(self.check_sat, 0, 1, 1, 1)
        self.check_sun = QtWidgets.QCheckBox(self.widget_8)
        self.check_sun.setObjectName("check_sun")
        self.gridLayout_2.addWidget(self.check_sun, 1, 1, 1, 1)
        self.check_wed = QtWidgets.QCheckBox(self.widget_8)
        self.check_wed.setChecked(True)
        self.check_wed.setObjectName("check_wed")
        self.gridLayout_2.addWidget(self.check_wed, 3, 0, 1, 1)
        self.check_thu = QtWidgets.QCheckBox(self.widget_8)
        self.check_thu.setChecked(True)
        self.check_thu.setObjectName("check_thu")
        self.gridLayout_2.addWidget(self.check_thu, 4, 0, 1, 1)
        self.check_fri = QtWidgets.QCheckBox(self.widget_8)
        self.check_fri.setChecked(True)
        self.check_fri.setObjectName("check_fri")
        self.gridLayout_2.addWidget(self.check_fri, 5, 0, 1, 1)
        self.check_tue = QtWidgets.QCheckBox(self.widget_8)
        self.check_tue.setChecked(True)
        self.check_tue.setObjectName("check_tue")
        self.gridLayout_2.addWidget(self.check_tue, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_8)
        self.line_8 = QtWidgets.QFrame(self.page_17)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_4.addWidget(self.line_8)
        self.toolBox.addItem(self.page_17, "")
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setEnabled(True)
        self.page_18.setGeometry(QtCore.QRect(0, 0, 217, 325))
        self.page_18.setObjectName("page_18")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_18)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.page_18)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.dateEdit_start = QtWidgets.QDateEdit(self.page_18)
        self.dateEdit_start.setCalendarPopup(True)
        self.dateEdit_start.setObjectName("dateEdit_start")
        self.verticalLayout_5.addWidget(self.dateEdit_start)
        self.label_13 = QtWidgets.QLabel(self.page_18)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.dateEdit_end = QtWidgets.QDateEdit(self.page_18)
        self.dateEdit_end.setCalendarPopup(True)
        self.dateEdit_end.setObjectName("dateEdit_end")
        self.verticalLayout_5.addWidget(self.dateEdit_end)
        self.widget_3 = QtWidgets.QWidget(self.page_18)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_range_button = QtWidgets.QPushButton(self.widget_3)
        self.add_range_button.setObjectName("add_range_button")
        self.horizontalLayout_3.addWidget(self.add_range_button)
        self.del_range_button = QtWidgets.QPushButton(self.widget_3)
        self.del_range_button.setObjectName("del_range_button")
        self.horizontalLayout_3.addWidget(self.del_range_button)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.treeWidget = QtWidgets.QTreeWidget(self.page_18)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_5.addWidget(self.treeWidget)
        self.create_charts_button = QtWidgets.QPushButton(self.page_18)
        self.create_charts_button.setObjectName("create_charts_button")
        self.verticalLayout_5.addWidget(self.create_charts_button)
        self.toolBox.addItem(self.page_18, "")
        self.page_20 = QtWidgets.QWidget()
        self.page_20.setEnabled(True)
        self.page_20.setGeometry(QtCore.QRect(0, 0, 218, 239))
        self.page_20.setObjectName("page_20")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_20)
        self.verticalLayout_8.setContentsMargins(7, 1, 1, 1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.page_20)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.verticalLayout_8.addWidget(self.treeWidget_2)
        self.widget_7 = QtWidgets.QWidget(self.page_20)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.toolBox.addItem(self.page_20, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 250))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 226, 198))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.webView_minimap = QtWebEngineWidgets.QWebEngineView(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView_minimap.sizePolicy().hasHeightForWidth())
        self.webView_minimap.setSizePolicy(sizePolicy)
        self.webView_minimap.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView_minimap.setObjectName("webView_minimap")
        self.verticalLayout_7.addWidget(self.webView_minimap)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QTabBar::tab:top {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent black;\n"
"    background-color: #54575B;\n"
"    padding: 5px;\n"
"    min-width: 50px;\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 5px solid #3daee9;\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover {\n"
"    background-color: #3daee9;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("")
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_11 = QtWidgets.QWidget(self.tab_4)
        self.widget_11.setStyleSheet("")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_11)
        self.label_2.setMaximumSize(QtCore.QSize(1000, 650))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icon/18135_splash_chart.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_11.addWidget(self.widget_11)
        self.widget = QtWidgets.QWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_new_proj = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_new_proj.setFont(font)
        self.pushButton_new_proj.setObjectName("pushButton_new_proj")
        self.horizontalLayout_2.addWidget(self.pushButton_new_proj)
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.pushButton_exit = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout_2.addWidget(self.pushButton_exit)
        self.verticalLayout_11.addWidget(self.widget)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.webView_map = QtWebEngineWidgets.QWebEngineView(self.tab_3)
        self.webView_map.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView_map.setObjectName("webView_map")
        self.verticalLayout_10.addWidget(self.webView_map)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1332, 26))
        self.menubar.setObjectName("menubar")
        self.menubar.setStyleSheet("QWidget {\n"
"    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    selection-background-color: #3daee9;\n"
"    selection-color: #eff0f1;\n"
"    background-clip: border;\n"
"    border-image: none;\n"
"    border: 0px transparent black;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QWidget:item:hover {\n"
"    background-color: #18465d;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QWidget:item:selected {\n"
"    background-color: #18465d;\n"
"}\n"
"QWidget:disabled {\n"
"    color: #454545;\n"
"    background-color: #31363b;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #31363b;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: transparent;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    border: 1px solid #76797C;\n"
"    background-color: #3daee9;\n"
"    color: #eff0f1;\n"
"    margin-bottom: -1px;\n"
"    padding-bottom: 1px;\n"
"}\n"
"\n"
"QMenu {\n"
"    border: 1px solid #76797C;\n"
"    color: #eff0f1;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenu::icon {\n"
"    margin: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: #31363b;\n"
"    padding: 5px 30px 5px 30px;\n"
"    border: 1px solid transparent;\n"
"    /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    color: #eff0f1;\n"
"}\n"
"QMenu::item:hover {\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 2px;\n"
"    background: lightblue;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        self.menuChartOptions = QtWidgets.QMenu(self.menubar)
        self.menuChartOptions.setObjectName("menuChartOptions")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionView_Extra_Time = QtWidgets.QAction(MainWindow)
        self.actionView_Extra_Time.setObjectName("actionView_Extra_Time")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())
        self.menubar.addAction(self.menuChartOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(5)
        self.toolBox.layout().setSpacing(7)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Travel Time and Probe Data Analytics Tool"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Analyst:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Agency:</span></p></body></html>"))
        self.label_agency.setText(_translate("MainWindow", "--"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Facility:</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "--"))
        self.label_project_name.setText(_translate("MainWindow", "--"))
        self.label_analyst.setText(_translate("MainWindow", "--"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Data quality assesment showing<br/>percent of possible sample available<br/>in the imported dataset.</p><p> Explore by direction or TMC</p></body></html>"))
        self.treeWidget_3.headerItem().setText(0, _translate("MainWindow", "Project"))
        self.pushButton_first_chart.setText(_translate("MainWindow", "Proceed to Step 1.2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_15), _translate("MainWindow", "Stage 1.1 Data Availability"))
        self.label_7.setText(_translate("MainWindow", "AM Peak Hours"))
        self.label_8.setText(_translate("MainWindow", "Midday Peak Hours"))
        self.label_9.setText(_translate("MainWindow", "PM Peak Hours"))
        self.pushButton_sec_chart.setText(_translate("MainWindow", "Proceed to Step 1.3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_16), _translate("MainWindow", "Stage 1.2 Spatial Scoping"))
        self.label_14.setText(_translate("MainWindow", "TMC Selection"))
        self.label_15.setText(_translate("MainWindow", "Congestion Stack Time Period"))
        self.label_10.setText(_translate("MainWindow", "to"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_19), _translate("MainWindow", "Stage 1.3 Temporal Scoping"))
        self.label_11.setText(_translate("MainWindow", "TMC Selection:"))
        self.check_mid.setText(_translate("MainWindow", "Midday"))
        self.check_am.setText(_translate("MainWindow", "AM"))
        self.check_pm.setText(_translate("MainWindow", "PM"))
        self.edit_trends_button.setText(_translate("MainWindow", "Edit..."))
        self.trend_label_am.setText(_translate("MainWindow", "TextLabel"))
        self.trend_label_pm.setText(_translate("MainWindow", "TextLabel"))
        self.trend_label_mid.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "Trends"))
        self.check_wkdy.setText(_translate("MainWindow", "Weekdays"))
        self.check_wknd.setText(_translate("MainWindow", "Weekends"))
        self.check_mon.setText(_translate("MainWindow", "Monday"))
        self.check_sat.setText(_translate("MainWindow", "Saturday"))
        self.check_sun.setText(_translate("MainWindow", "Sunday"))
        self.check_wed.setText(_translate("MainWindow", "Wednesday"))
        self.check_thu.setText(_translate("MainWindow", "Thursday"))
        self.check_fri.setText(_translate("MainWindow", "Friday"))
        self.check_tue.setText(_translate("MainWindow", "Tuesday"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_17), _translate("MainWindow", "Stage 1.4 Trend Analysis"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Please select two date ranges for<br/>Before/After Analysis:</p><p>Start Date:</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "End Date:"))
        self.add_range_button.setText(_translate("MainWindow", "Add Range"))
        self.del_range_button.setText(_translate("MainWindow", "Delete Range"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Date Range"))
        self.create_charts_button.setText(_translate("MainWindow", "Proceed To Stage 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_18), _translate("MainWindow", "Stage 1.5 Set Analysis"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "#) TMC Code"))
        self.treeWidget_2.headerItem().setText(1, _translate("MainWindow", "Name"))
        self.treeWidget_2.headerItem().setText(2, _translate("MainWindow", "Dir"))
        self.treeWidget_2.headerItem().setText(3, _translate("MainWindow", "TMC Mi"))
        self.treeWidget_2.headerItem().setText(4, _translate("MainWindow", "Total Mi"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Selected Length:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "0.0 miles"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_20), _translate("MainWindow", "Stage 2: Comparison Analysis"))
        self.pushButton_new_proj.setText(_translate("MainWindow", "Load Data"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Welcome"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Facility Map"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "View"))
        self.menuChartOptions.setTitle(_translate("MainWindow", "Chart Options"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "Project"))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load Data"))
        self.actionView_Extra_Time.setText(_translate("MainWindow", "View Extra Time"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

from PyQt5 import QtWebEngineWidgets
