# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_test.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(210, 10, 891, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.webView = QtWebKitWidgets.QWebView(self.tab)
        self.webView.setGeometry(QtCore.QRect(10, 10, 861, 651))
        self.webView.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.webView_2 = QtWebKitWidgets.QWebView(self.tab_2)
        self.webView_2.setGeometry(QtCore.QRect(10, 10, 861, 651))
        self.webView_2.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView_2.setObjectName("webView_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.webView_3 = QtWebKitWidgets.QWebView(self.tab_3)
        self.webView_3.setGeometry(QtCore.QRect(10, 10, 861, 651))
        self.webView_3.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView_3.setObjectName("webView_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 580, 191, 131))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 189, 129))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(170, 0, 20, 131))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 171, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 201, 131))
        self.label.setObjectName("label")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(10, 140, 191, 431))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 191, 214))
        self.page.setObjectName("page")
        self.treeWidget = QtWidgets.QTreeWidget(self.page)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 191, 192))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 191, 214))
        self.page_2.setObjectName("page_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 191, 211))
        self.listWidget_2.setObjectName("listWidget_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.checkBox = QtWidgets.QCheckBox(self.page_4)
        self.checkBox.setGeometry(QtCore.QRect(0, 10, 191, 20))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 40, 191, 20))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_3.setGeometry(QtCore.QRect(0, 70, 191, 20))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_4.setGeometry(QtCore.QRect(0, 100, 191, 20))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_5.setGeometry(QtCore.QRect(0, 130, 191, 20))
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.dateEdit = QtWidgets.QDateEdit(self.page_5)
        self.dateEdit.setGeometry(QtCore.QRect(-1, 30, 191, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.page_5)
        self.label_5.setGeometry(QtCore.QRect(4, 0, 181, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setGeometry(QtCore.QRect(0, 60, 191, 16))
        self.label_6.setObjectName("label_6")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.page_5)
        self.dateEdit_2.setGeometry(QtCore.QRect(0, 90, 181, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_2 = QtWidgets.QLabel(self.page_6)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 191, 20))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.page_6)
        self.horizontalSlider.setGeometry(QtCore.QRect(0, 30, 191, 19))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.page_6)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 191, 20))
        self.label_3.setObjectName("label_3")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.page_6)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(0, 90, 191, 19))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setInvertedAppearance(False)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_4 = QtWidgets.QLabel(self.page_6)
        self.label_4.setGeometry(QtCore.QRect(0, 120, 191, 16))
        self.label_4.setObjectName("label_4")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.page_6)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(0, 150, 191, 19))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.toolBox.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.toolBox.addItem(self.page_7, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 191, 214))
        self.page_3.setObjectName("page_3")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 191, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 40, 191, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.toolBox.addItem(self.page_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionView_Extra_Time = QtWidgets.QAction(MainWindow)
        self.actionView_Extra_Time.setObjectName("actionView_Extra_Time")
        self.menuView.addAction(self.actionView_Extra_Time)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Welcome"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Chart 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Chart 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Chart 3"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project: </span>Example</p><p><span style=\" font-weight:600;\">Analyst: </span>JLT</p><p><span style=\" font-weight:600;\">Agency: </span>KAI</p><p><span style=\" font-weight:600;\">Description:</span></p></body></html>"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Dataset"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "I-40 Weekday"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Eastbound"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Study Period #1"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Study Period #2"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Westbound"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Study Period #1"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "I-40 Weekend"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Eastbound"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Westbound"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "I-95 Weekday"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Eastbound"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Westbound"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Dataset"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Data Type"))
        self.checkBox.setText(_translate("MainWindow", "Speed Band"))
        self.checkBox_2.setText(_translate("MainWindow", "Travel Time Index"))
        self.checkBox_3.setText(_translate("MainWindow", "Extra Time Comparison"))
        self.checkBox_4.setText(_translate("MainWindow", "Reliability PDF/CDF"))
        self.checkBox_5.setText(_translate("MainWindow", "Delay"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Analysis Type"))
        self.label_5.setText(_translate("MainWindow", "Starting Date"))
        self.label_6.setText(_translate("MainWindow", "Ending Date"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Date Ranges"))
        self.label_2.setText(_translate("MainWindow", "Filter #1"))
        self.label_3.setText(_translate("MainWindow", "Filter #2"))
        self.label_4.setText(_translate("MainWindow", "Filter #3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "Data Filtering"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", "Data Resolution"))
        self.pushButton.setText(_translate("MainWindow", "Summary Report"))
        self.pushButton_2.setText(_translate("MainWindow", "Detailed Report"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Reports"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load Data"))
        self.actionView_Extra_Time.setText(_translate("MainWindow", "View Extra Time"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

