# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_test.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.toolBox = QtWidgets.QToolBox(self.widget_2)
        self.toolBox.setObjectName("toolBox")
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setGeometry(QtCore.QRect(0, 0, 178, 258))
        self.page_15.setObjectName("page_15")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_15)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.page_15)
        self.treeWidget_3.setObjectName("treeWidget_3")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.treeWidget_3)
        self.toolBox.addItem(self.page_15, "")
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setGeometry(QtCore.QRect(0, 0, 178, 258))
        self.page_16.setObjectName("page_16")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_16)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_4 = QtWidgets.QListWidget(self.page_16)
        self.listWidget_4.setObjectName("listWidget_4")
        self.verticalLayout_3.addWidget(self.listWidget_4)
        self.toolBox.addItem(self.page_16, "")
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setGeometry(QtCore.QRect(0, 0, 178, 258))
        self.page_17.setObjectName("page_17")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_17)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_11 = QtWidgets.QCheckBox(self.page_17)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_4.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.page_17)
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_4.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.page_17)
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_4.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.page_17)
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_4.addWidget(self.checkBox_14)
        self.checkBox_15 = QtWidgets.QCheckBox(self.page_17)
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_4.addWidget(self.checkBox_15)
        self.toolBox.addItem(self.page_17, "")
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setGeometry(QtCore.QRect(0, 0, 178, 258))
        self.page_18.setObjectName("page_18")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_18)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.page_18)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.dateEdit_5 = QtWidgets.QDateEdit(self.page_18)
        self.dateEdit_5.setCalendarPopup(True)
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.verticalLayout_5.addWidget(self.dateEdit_5)
        self.label_13 = QtWidgets.QLabel(self.page_18)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.dateEdit_6 = QtWidgets.QDateEdit(self.page_18)
        self.dateEdit_6.setCalendarPopup(True)
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.verticalLayout_5.addWidget(self.dateEdit_6)
        self.toolBox.addItem(self.page_18, "")
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setGeometry(QtCore.QRect(0, 0, 178, 258))
        self.page_19.setObjectName("page_19")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_19)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.page_19)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.horizontalSlider_7 = QtWidgets.QSlider(self.page_19)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.verticalLayout_6.addWidget(self.horizontalSlider_7)
        self.label_15 = QtWidgets.QLabel(self.page_19)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.horizontalSlider_8 = QtWidgets.QSlider(self.page_19)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setInvertedAppearance(False)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.verticalLayout_6.addWidget(self.horizontalSlider_8)
        self.label_16 = QtWidgets.QLabel(self.page_19)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.horizontalSlider_9 = QtWidgets.QSlider(self.page_19)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.verticalLayout_6.addWidget(self.horizontalSlider_9)
        self.toolBox.addItem(self.page_19, "")
        self.page_20 = QtWidgets.QWidget()
        self.page_20.setGeometry(QtCore.QRect(0, 0, 178, 258))
        self.page_20.setObjectName("page_20")
        self.toolBox.addItem(self.page_20, "")
        self.page_21 = QtWidgets.QWidget()
        self.page_21.setGeometry(QtCore.QRect(0, 0, 178, 258))
        self.page_21.setObjectName("page_21")
        self.formLayout = QtWidgets.QFormLayout(self.page_21)
        self.formLayout.setContentsMargins(1, 1, 1, 1)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_21)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_21)
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.pushButton_6)
        self.toolBox.addItem(self.page_21, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 155, 89))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_7.addWidget(self.textEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../NPMRDS_Data_Tool/FHWA-1080x353.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_11.addWidget(self.textEdit_2)
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_11.addWidget(self.widget)
        self.widget_2.raise_()
        self.textEdit_2.raise_()
        self.widget.raise_()
        self.label_2.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.webView = QtWebKitWidgets.QWebView(self.tab)
        self.webView.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout_8.addWidget(self.webView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.webView_2 = QtWebKitWidgets.QWebView(self.tab_2)
        self.webView_2.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView_2.setObjectName("webView_2")
        self.verticalLayout_9.addWidget(self.webView_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.webView_3 = QtWebKitWidgets.QWebView(self.tab_3)
        self.webView_3.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView_3.setObjectName("webView_3")
        self.verticalLayout_10.addWidget(self.webView_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionView_Extra_Time = QtWidgets.QAction(MainWindow)
        self.actionView_Extra_Time.setObjectName("actionView_Extra_Time")
        self.menuView.addAction(self.actionView_Extra_Time)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project: </span>Example</p><p><span style=\" font-weight:600;\">Analyst: </span>JLT</p><p><span style=\" font-weight:600;\">Agency: </span>KAI</p><p><span style=\" font-weight:600;\">Description:</span></p></body></html>"))
        self.treeWidget_3.headerItem().setText(0, _translate("MainWindow", "Dataset"))
        __sortingEnabled = self.treeWidget_3.isSortingEnabled()
        self.treeWidget_3.setSortingEnabled(False)
        self.treeWidget_3.topLevelItem(0).setText(0, _translate("MainWindow", "I-40 Weekday"))
        self.treeWidget_3.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Eastbound"))
        self.treeWidget_3.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Study Period #1"))
        self.treeWidget_3.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Study Period #2"))
        self.treeWidget_3.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Westbound"))
        self.treeWidget_3.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Study Period #1"))
        self.treeWidget_3.topLevelItem(1).setText(0, _translate("MainWindow", "I-40 Weekend"))
        self.treeWidget_3.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Eastbound"))
        self.treeWidget_3.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Westbound"))
        self.treeWidget_3.topLevelItem(2).setText(0, _translate("MainWindow", "I-95 Weekday"))
        self.treeWidget_3.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Eastbound"))
        self.treeWidget_3.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Westbound"))
        self.treeWidget_3.setSortingEnabled(__sortingEnabled)
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_15), _translate("MainWindow", "Dataset"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_16), _translate("MainWindow", "Data Type"))
        self.checkBox_11.setText(_translate("MainWindow", "Speed Band"))
        self.checkBox_12.setText(_translate("MainWindow", "Travel Time Index"))
        self.checkBox_13.setText(_translate("MainWindow", "Extra Time Comparison"))
        self.checkBox_14.setText(_translate("MainWindow", "Reliability PDF/CDF"))
        self.checkBox_15.setText(_translate("MainWindow", "Delay"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_17), _translate("MainWindow", "Analysis Type"))
        self.label_12.setText(_translate("MainWindow", "Starting Date"))
        self.label_13.setText(_translate("MainWindow", "Ending Date"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_18), _translate("MainWindow", "Date Ranges"))
        self.label_14.setText(_translate("MainWindow", "Filter #1"))
        self.label_15.setText(_translate("MainWindow", "Filter #2"))
        self.label_16.setText(_translate("MainWindow", "Filter #3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_19), _translate("MainWindow", "Data Filtering"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_20), _translate("MainWindow", "Data Resolution"))
        self.pushButton_5.setText(_translate("MainWindow", "Summary Report"))
        self.pushButton_6.setText(_translate("MainWindow", "Detailed Report"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_21), _translate("MainWindow", "Reports"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; color:#00007f;\">Sketch Planning Advanced Tool</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt; color:#00007f;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; color:#00007f;\">Developed by Kittelson and Associates, Inc.</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Create New"))
        self.pushButton_2.setText(_translate("MainWindow", "Open Existing"))
        self.pushButton_3.setText(_translate("MainWindow", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Welcome"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Chart 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Chart 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Chart 3"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load Data"))
        self.actionView_Extra_Time.setText(_translate("MainWindow", "View Extra Time"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

