from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need
# fine tuning.
buildOptions = dict(packages = ['PyQt5', 'flask', 'jinja2', 'asyncio'], excludes = ['tkinter', 'pandas',
                                                                                    'PyQt5.uic',
                                                                                    'numpy',
                                                                                    'scipy',
                                                                                    'matplotlib',
                                                                                    'lxml',
                                                                                    'bottleneck',
                                                                                    'adodbapi',
                                                                                    'alabaster',
                                                                                    'babel',
                                                                                    'backports',
                                                                                    'boto',
                                                                                    'chardet',
                                                                                    'bs4',
                                                                                    'cffi',
                                                                                    'cloudpickle',
                                                                                    'cryptography',
                                                                                    'colorama',
                                                                                    'Cython',
                                                                                    'curses',
                                                                                    'dill',
                                                                                    'dateutil',
                                                                                    'dbm',
                                                                                    'distutils',
                                                                                    'docutils',
                                                                                    'idna',
                                                                                    'imagesize',
                                                                                    'ipython_genutils',
                                                                                    'ipykernel',
                                                                                    'IPython',
                                                                                    'lib2to3',
                                                                                    'jupyter_client',
                                                                                    'jupyter_core',
                                                                                    'mpl-data',
                                                                                    'mpl_toolkits',
                                                                                    'nose',
                                                                                    'nbconvert',
                                                                                    'nbformat',
                                                                                    'openpyxl',
                                                                                    'notebook',
                                                                                    'numexpr',
                                                                                    'PIL',
                                                                                    'patsy',
                                                                                    'pyasn1',
                                                                                    'prompt_toolkit',
                                                                                    'py',
                                                                                    'pycparser',
                                                                                    'pydoc_data',
                                                                                    'pygments',
                                                                                    'pyximport',
                                                                                    'pytz',
                                                                                    'pywin',
                                                                                    'sqlalchemy',
                                                                                    'sphinx',
                                                                                    'statsmodels',
                                                                                    'tables',
                                                                                    'sqlite3',
                                                                                    'unittest',
                                                                                    'tornado',
                                                                                    'traitlets',
                                                                                    'win_unicode_console',
                                                                                    'wcwidth',
                                                                                    'xlrd',
                                                                                    'win32com',
                                                                                    'wsgiref',
                                                                                    'xlwt',
                                                                                    'xlsxwriter',
                                                                                    'zmq',
                                                                                    'xml',
                                                                                    'xmlrpc',
                                                                                    'lxml'])
import sys
base = 'Win32GUI' if sys.platform=='win32' else None

executables = [
    Executable('fhwa_spl.py', base=base)
]

setup(name='FHWA_SPL',
      version = '1.0',
      description = '',
      options = dict(build_exe = buildOptions),
      executables = executables)
